<a href="https://colab.research.google.com/github/mromanenko095/ml-assignments/blob/main/Pandas_Matplotlib_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!gdown 1KWlcYkMkDIZdATT2TTcnIfudNP-PSUci  # подключение к диску по id
# Все сохранилось в среду колаба

Downloading...
From: https://drive.google.com/uc?id=1KWlcYkMkDIZdATT2TTcnIfudNP-PSUci
To: /content/titanic.csv
100% 61.2k/61.2k [00:00<00:00, 52.7MB/s]

In [6]:
!ls  # смотрим что лежит в директории

drive  sample_data  titanic.csv

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
!cp /content/titanic.csv /content/drive/MyDrive  # копируем файл на диск, можно через mv (move)

In [8]:
import pandas as pd

# Series

In [12]:
a = [1, 7, 2]

series = pd.Series(a)

series

0    1
1    7
2    2
dtype: int64

In [16]:
series.loc[1]

np.int64(7)

In [15]:
series.iloc[1]

np.int64(7)

In [18]:
series = pd.Series(a, index=['x', 'y', 'z'])
series

x    1
y    7
z    2
dtype: int64

In [19]:
series.loc['x']

np.int64(1)

# DataFrame

In [24]:
data = {
    'calories': [420, 200, 438],
    'duration': [23, 21, 28]
}

# Ключи - названия строк

df = pd.DataFrame(data)
df.head()

   calories  duration
0       420        23
1       200        21
2       438        28

In [25]:
# Выведем столбец calories
df['calories']

0    420
1    200
2    438
Name: calories, dtype: int64

In [27]:
# Выведем строку 1
df.iloc[1]

calories    200
duration     21
Name: 1, dtype: int64

In [28]:
df.loc[1]

calories    200
duration     21
Name: 1, dtype: int64

# Создание DataFrame из файла

In [32]:
df = pd.read_csv('/content/titanic.csv', index_col='PassengerId')
df.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [35]:
df.sample(3)  # рандомная строка

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
332,0,1,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S
109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,NaN,S
203,0,3,"Johanson, Mr. Jakob Alfred",male,34.0,0,0,3101264,6.4958,NaN,S

In [36]:
df.tail(3)  # последние строки

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [37]:
df.loc[6]  # значения всех столбцов для этой строки

Survived                   0
Pclass                     3
Name        Moran, Mr. James
Sex                     male
Age                      NaN
SibSp                      0
Parch                      0
Ticket                330877
Fare                  8.4583
Cabin                    NaN
Embarked                   Q
Name: 6, dtype: object

In [38]:
df.loc[6:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [39]:
df.iloc[6:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [43]:
df.loc[[6, 8, 16]]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [44]:
df['Survived']

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: int64

In [45]:
df.loc[9, 'Survived']

np.int64(1)

In [46]:
df.loc[7:9, 'Survived']

PassengerId
7    0
8    0
9    1
Name: Survived, dtype: int64

In [47]:
df.loc[[7, 8, 92, 33], 'Survived']

PassengerId
7     0
8     0
92    0
33    1
Name: Survived, dtype: int64